# -*- encoding: utf-8 -*-

=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "templatefox/version"

Gem::Specification.new do |s|
  s.name        = "templatefox"
  s.version     = TemplateFox::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["TemplateFox"]
  s.email       = ["support@pdftemplateapi.com"]
  s.homepage    = "https://pdftemplateapi.com"
  s.summary     = "Official TemplateFox Ruby SDK"
  s.description = "Ruby SDK for TemplateFox - Generate PDFs from HTML templates via API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {
    "source_code_uri"   => "https://github.com/TemplateFoxPDF/rubysdk",
    "bug_tracker_uri"   => "https://github.com/TemplateFoxPDF/rubysdk/issues",
    "documentation_uri" => "https://pdftemplateapi.com/docs",
    "homepage_uri"      => "https://pdftemplateapi.com"
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
