=begin
#TemplateFox API

#Generate PDFs from HTML templates via API. Design once, generate thousands.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::AccountApi)
    end
  end

  # unit tests for get_account
  # Get account info
  # Get account information including remaining credits.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** Check credit balance before performing operations.  **No credits consumed:** This is a read-only endpoint.
  # @param [Hash] opts the optional parameters
  # @return [AccountInfoResponse]
  describe 'get_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_transactions
  # List transactions
  # List transaction history for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Pagination:** Use &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  **Transaction types:** - &#x60;PDFGEN&#x60;: PDF generation (consumes credits) - &#x60;REFUND&#x60;: Credit refund (on failed generation) - &#x60;PURCHASE&#x60;: Credit purchase - &#x60;BONUS&#x60;: Bonus credits  **Credits field:** - Positive value &#x3D; credits consumed - Negative value &#x3D; credits added  **No credits consumed:** This is a read-only endpoint.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of records to return
  # @option opts [Integer] :offset Number of records to skip
  # @return [TransactionsResponse]
  describe 'list_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
