=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.13.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::AgentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AgentApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::AgentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AgentApi' do
    it 'should create an instance of AgentApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::AgentApi)
    end
  end

  # unit tests for create_agent_template
  # Create a template with the authoring agent
  # Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
  # @param create_agent_template_request 
  # @param [Hash] opts the optional parameters
  # @return [AgentJobCreatedResponse]
  describe 'create_agent_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_agent_job
  # Get authoring-agent job status
  # Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
  # @param job_id Job UUID
  # @param [Hash] opts the optional parameters
  # @return [AgentJobStatusResponse]
  describe 'get_agent_job test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revise_agent_template
  # Revise a template with the authoring agent
  # Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
  # @param template_id Template short ID (12 characters)
  # @param revise_agent_template_request 
  # @param [Hash] opts the optional parameters
  # @return [AgentJobCreatedResponse]
  describe 'revise_agent_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
