=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.12.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::ImageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ImageApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::ImageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImageApi' do
    it 'should create an instance of ImageApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::ImageApi)
    end
  end

  # unit tests for create_image
  # Generate image from template
  # Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |----------|-------------| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param create_image_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateImageResponse]
  describe 'create_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
