=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::IntegrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IntegrationsApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::IntegrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationsApi' do
    it 'should create an instance of IntegrationsApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::IntegrationsApi)
    end
  end

  # unit tests for delete_s3_config
  # Delete S3 configuration
  # Delete S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You&#39;ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param [Hash] opts the optional parameters
  # @return [S3SuccessResponse]
  describe 'delete_s3_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_s3_config
  # Get S3 configuration
  # Get current S3 storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param [Hash] opts the optional parameters
  # @return [S3ConfigResponse]
  describe 'get_s3_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for save_s3_config
  # Save S3 configuration
  # Save or update S3-compatible storage configuration.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: &#x60;secret_access_key&#x60; is required - For updates: Omit &#x60;secret_access_key&#x60; to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param s3_config_request 
  # @param [Hash] opts the optional parameters
  # @return [S3SuccessResponse]
  describe 'save_s3_config test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_s3_connection
  # Test S3 connection
  # Test S3 connection with stored credentials.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using &#x60;POST /v1/integrations/s3&#x60;  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param [Hash] opts the optional parameters
  # @return [S3TestResponse]
  describe 'test_s3_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
