=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::PDFAsyncApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PDFAsyncApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::PDFAsyncApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PDFAsyncApi' do
    it 'should create an instance of PDFAsyncApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::PDFAsyncApi)
    end
  end

  # unit tests for create_pdf_async
  # Generate PDF asynchronously
  # Queue a PDF generation job for async processing.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## How It Works  1. Submit a job with template and data 2. Receive a &#x60;job_id&#x60; immediately 3. Poll &#x60;/v1/pdf/status/{job_id}&#x60; for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can&#39;t wait for synchronous response - You want webhook notifications  ## Webhooks  If &#x60;webhook_url&#x60; is provided, we&#39;ll POST to it when the job completes or fails:  &#x60;&#x60;&#x60;json {     \&quot;event\&quot;: \&quot;pdf.completed\&quot;,     \&quot;job_id\&quot;: \&quot;...\&quot;,     \&quot;status\&quot;: \&quot;completed\&quot;,     \&quot;result\&quot;: {         \&quot;url\&quot;: \&quot;https://...\&quot;,         \&quot;filename\&quot;: \&quot;invoice.pdf\&quot;     } } &#x60;&#x60;&#x60;  Webhooks include HMAC-SHA256 signature in &#x60;X-TemplateFox-Signature&#x60; header if you provide a &#x60;webhook_secret&#x60;.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
  # @param create_async_pdf_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateAsyncPdfResponse]
  describe 'create_pdf_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_pdf_job_status
  # Get PDF job status
  # Get the current status of an async PDF generation job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |--------|-------------| | &#x60;pending&#x60; | Job is queued, waiting to be processed | | &#x60;processing&#x60; | Job is being processed | | &#x60;completed&#x60; | PDF generated successfully | | &#x60;failed&#x60; | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [JobStatusResponse]
  describe 'get_pdf_job_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pdf_jobs
  # List PDF jobs
  # List async PDF generation jobs for your team.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  Supports pagination and filtering by status.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @option opts [JobStatus] :status 
  # @return [JobListResponse]
  describe 'list_pdf_jobs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
