=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::PDFApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PDFApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::PDFApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PDFApi' do
    it 'should create an instance of PDFApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::PDFApi)
    end
  end

  # unit tests for create_pdf
  # Generate PDF from template
  # Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;data&#x60; | object | ✅ Yes | Key-value data to render in template | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; | | &#x60;expiration&#x60; | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - &#x60;url&#x60; (default): PDF is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param create_pdf_request 
  # @param [Hash] opts the optional parameters
  # @return [CreatePdfResponse]
  describe 'create_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
