=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.10.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::PDFToolsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PDFToolsApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::PDFToolsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PDFToolsApi' do
    it 'should create an instance of PDFToolsApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::PDFToolsApi)
    end
  end

  # unit tests for extract_pdf_pages
  # Extract pages from a PDF
  # Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
  # @param extract_pdf_pages_request 
  # @param [Hash] opts the optional parameters
  # @return [PdfToolsResponse]
  describe 'extract_pdf_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merge_pdf
  # Merge PDFs
  # Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
  # @param merge_pdf_request 
  # @param [Hash] opts the optional parameters
  # @return [PdfToolsResponse]
  describe 'merge_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_pdf
  # Rotate pages of a PDF
  # Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
  # @param rotate_pdf_request 
  # @param [Hash] opts the optional parameters
  # @return [PdfToolsResponse]
  describe 'rotate_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
