=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TemplateFox::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplatesApi' do
  before do
    # run before each test
    @api_instance = TemplateFox::TemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplatesApi' do
    it 'should create an instance of TemplatesApi' do
      expect(@api_instance).to be_instance_of(TemplateFox::TemplatesApi)
    end
  end

  # unit tests for get_template_fields
  # Get template fields
  # Get the dynamic fields for a template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: &#x60;key&#x60;, &#x60;label&#x60;, &#x60;type&#x60;, &#x60;required&#x60;, optional &#x60;helpText&#x60;, and optional &#x60;spec&#x60; (for array fields).  **Field types:** - &#x60;string&#x60;: Text input - &#x60;integer&#x60;: Integer number - &#x60;number&#x60;: Decimal number - &#x60;boolean&#x60;: True/False checkbox - &#x60;array&#x60;: Array of items with nested &#x60;spec&#x60; defining item structure  **Array fields:** When a field is an array of objects, the response includes a &#x60;spec&#x60; array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<TemplateField>]
  describe 'get_template_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_templates
  # List templates
  # List all templates for the authenticated user.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
  # @param [Hash] opts the optional parameters
  # @return [TemplatesListResponse]
  describe 'list_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
