=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.1.1.dev2+gfe6303fdd.d20260209

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::AccountInfoResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::AccountInfoResponse do
  #let(:instance) { TemplateFox::AccountInfoResponse.new }

  describe 'test an instance of AccountInfoResponse' do
    it 'should create an instance of AccountInfoResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::AccountInfoResponse)
    end
  end

  describe 'test attribute "credits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
