=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.11.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::AppRoutersV1DeliveryExportType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::AppRoutersV1DeliveryExportType do
  #let(:instance) { TemplateFox::AppRoutersV1DeliveryExportType.new }

  describe 'test an instance of AppRoutersV1DeliveryExportType' do
    it 'should create an instance of AppRoutersV1DeliveryExportType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::AppRoutersV1DeliveryExportType)
    end
  end

end
