=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::ExportType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::ExportType do
  #let(:instance) { TemplateFox::ExportType.new }

  describe 'test an instance of ExportType' do
    it 'should create an instance of ExportType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::ExportType)
    end
  end

end
