=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.12.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::ImageFormat
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::ImageFormat do
  #let(:instance) { TemplateFox::ImageFormat.new }

  describe 'test an instance of ImageFormat' do
    it 'should create an instance of ImageFormat' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::ImageFormat)
    end
  end

end
