=begin
#TemplateFox API

#Generate PDFs from HTML templates via API. Design once, generate thousands.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::LocationInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::LocationInner do
end
