=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.10.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::PdfInput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::PdfInput do
  #let(:instance) { TemplateFox::PdfInput.new }

  describe 'test an instance of PdfInput' do
    it 'should create an instance of PdfInput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::PdfInput)
    end
  end

  describe 'test attribute "pdf_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pdf_base64"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
