=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::S3TestResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::S3TestResponse do
  #let(:instance) { TemplateFox::S3TestResponse.new }

  describe 'test an instance of S3TestResponse' do
    it 'should create an instance of S3TestResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::S3TestResponse)
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
