=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.9.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::SetDefaultVersionRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::SetDefaultVersionRequest do
  #let(:instance) { TemplateFox::SetDefaultVersionRequest.new }

  describe 'test an instance of SetDefaultVersionRequest' do
    it 'should create an instance of SetDefaultVersionRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::SetDefaultVersionRequest)
    end
  end

  describe 'test attribute "version_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
