=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.1.3

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::TemplateField
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::TemplateField do
  #let(:instance) { TemplateFox::TemplateField.new }

  describe 'test an instance of TemplateField' do
    it 'should create an instance of TemplateField' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::TemplateField)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "required"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "help_text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
