=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.9.4

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TemplateFox::VersionsListResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TemplateFox::VersionsListResponse do
  #let(:instance) { TemplateFox::VersionsListResponse.new }

  describe 'test an instance of VersionsListResponse' do
    it 'should create an instance of VersionsListResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TemplateFox::VersionsListResponse)
    end
  end

  describe 'test attribute "versions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
