=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

# Common files
require 'templatefox/api_client'
require 'templatefox/api_error'
require 'templatefox/api_model_base'
require 'templatefox/version'
require 'templatefox/configuration'

# Models
require 'templatefox/models/account_info_response'
require 'templatefox/models/app_routers_v1_pdf_async_export_type'
require 'templatefox/models/app_routers_v1_pdf_export_type'
require 'templatefox/models/create_async_pdf_request'
require 'templatefox/models/create_async_pdf_response'
require 'templatefox/models/create_pdf_request'
require 'templatefox/models/create_pdf_response'
require 'templatefox/models/http_validation_error'
require 'templatefox/models/job_list_response'
require 'templatefox/models/job_status'
require 'templatefox/models/job_status_response'
require 'templatefox/models/location_inner'
require 'templatefox/models/s3_config_request'
require 'templatefox/models/s3_config_response'
require 'templatefox/models/s3_success_response'
require 'templatefox/models/s3_test_response'
require 'templatefox/models/template_field'
require 'templatefox/models/template_field_spec'
require 'templatefox/models/template_list_item'
require 'templatefox/models/templates_list_response'
require 'templatefox/models/transaction'
require 'templatefox/models/transactions_response'
require 'templatefox/models/validation_error'

# APIs
require 'templatefox/api/account_api'
require 'templatefox/api/integrations_api'
require 'templatefox/api/pdf_api'
require 'templatefox/api/pdf_async_api'
require 'templatefox/api/templates_api'

module TemplateFox
  class << self
    # Customize default settings for the SDK using block.
    #   TemplateFox.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
