=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.13.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module TemplateFox
  # Optional brand constraints passed to the agent.
  class BrandInputs < ApiModelBase
    # Brand colors as hex strings, e.g. ['#0C3C5F', '#E27D28']
    attr_accessor :colors

    # Preferred font families. Non-built-in fonts are substituted with the closest built-in and noted in the result.
    attr_accessor :fonts

    # Public https:// URLs of assets (logo, photos) the agent may use.
    attr_accessor :asset_urls

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'colors' => :'colors',
        :'fonts' => :'fonts',
        :'asset_urls' => :'asset_urls'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'colors' => :'Array<String>',
        :'fonts' => :'Array<String>',
        :'asset_urls' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::BrandInputs` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::BrandInputs`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'colors')
        if (value = attributes[:'colors']).is_a?(Array)
          self.colors = value
        end
      end

      if attributes.key?(:'fonts')
        if (value = attributes[:'fonts']).is_a?(Array)
          self.fonts = value
        end
      end

      if attributes.key?(:'asset_urls')
        if (value = attributes[:'asset_urls']).is_a?(Array)
          self.asset_urls = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@colors.nil? && @colors.length > 8
        invalid_properties.push('invalid value for "colors", number of items must be less than or equal to 8.')
      end

      if !@fonts.nil? && @fonts.length > 4
        invalid_properties.push('invalid value for "fonts", number of items must be less than or equal to 4.')
      end

      if !@asset_urls.nil? && @asset_urls.length > 5
        invalid_properties.push('invalid value for "asset_urls", number of items must be less than or equal to 5.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@colors.nil? && @colors.length > 8
      return false if !@fonts.nil? && @fonts.length > 4
      return false if !@asset_urls.nil? && @asset_urls.length > 5
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] colors Value to be assigned
    def colors=(colors)
      if colors.nil?
        fail ArgumentError, 'colors cannot be nil'
      end

      if colors.length > 8
        fail ArgumentError, 'invalid value for "colors", number of items must be less than or equal to 8.'
      end

      @colors = colors
    end

    # Custom attribute writer method with validation
    # @param [Object] fonts Value to be assigned
    def fonts=(fonts)
      if fonts.nil?
        fail ArgumentError, 'fonts cannot be nil'
      end

      if fonts.length > 4
        fail ArgumentError, 'invalid value for "fonts", number of items must be less than or equal to 4.'
      end

      @fonts = fonts
    end

    # Custom attribute writer method with validation
    # @param [Object] asset_urls Value to be assigned
    def asset_urls=(asset_urls)
      if asset_urls.nil?
        fail ArgumentError, 'asset_urls cannot be nil'
      end

      if asset_urls.length > 5
        fail ArgumentError, 'invalid value for "asset_urls", number of items must be less than or equal to 5.'
      end

      @asset_urls = asset_urls
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          colors == o.colors &&
          fonts == o.fonts &&
          asset_urls == o.asset_urls
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [colors, fonts, asset_urls].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
