=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.11.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module TemplateFox
  # Request model for image generation
  class CreateImageRequest < ApiModelBase
    # Template short ID (12 characters)
    attr_accessor :template_id

    attr_accessor :modifications

    # Optional key-value data merged into `{{ }}` template variables. For most image templates, prefer `modifications` instead.
    attr_accessor :data

    # Output image format: `png` (default), `jpeg` or `webp`.
    attr_accessor :format

    attr_accessor :width

    # Compression quality for `jpeg`/`webp` (1-100). Ignored for `png`.
    attr_accessor :quality

    # Export format: `url` uploads to CDN and returns URL, `binary` returns raw image bytes
    attr_accessor :export_type

    # URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to `url` export type.
    attr_accessor :expiration

    attr_accessor :filename

    # Upload to your configured S3 bucket instead of CDN
    attr_accessor :store_s3

    attr_accessor :s3_filepath

    attr_accessor :s3_bucket

    attr_accessor :version

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'template_id' => :'template_id',
        :'modifications' => :'modifications',
        :'data' => :'data',
        :'format' => :'format',
        :'width' => :'width',
        :'quality' => :'quality',
        :'export_type' => :'export_type',
        :'expiration' => :'expiration',
        :'filename' => :'filename',
        :'store_s3' => :'store_s3',
        :'s3_filepath' => :'s3_filepath',
        :'s3_bucket' => :'s3_bucket',
        :'version' => :'version'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'template_id' => :'String',
        :'modifications' => :'Array<Modification>',
        :'data' => :'Hash<String, Object>',
        :'format' => :'ImageFormat',
        :'width' => :'Integer',
        :'quality' => :'Integer',
        :'export_type' => :'AppRoutersV1DeliveryExportType',
        :'expiration' => :'Integer',
        :'filename' => :'String',
        :'store_s3' => :'Boolean',
        :'s3_filepath' => :'String',
        :'s3_bucket' => :'String',
        :'version' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'modifications',
        :'width',
        :'filename',
        :'s3_filepath',
        :'s3_bucket',
        :'version'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::CreateImageRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::CreateImageRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      else
        self.template_id = nil
      end

      if attributes.key?(:'modifications')
        if (value = attributes[:'modifications']).is_a?(Array)
          self.modifications = value
        end
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      end

      if attributes.key?(:'format')
        self.format = attributes[:'format']
      end

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      end

      if attributes.key?(:'quality')
        self.quality = attributes[:'quality']
      else
        self.quality = 85
      end

      if attributes.key?(:'export_type')
        self.export_type = attributes[:'export_type']
      end

      if attributes.key?(:'expiration')
        self.expiration = attributes[:'expiration']
      else
        self.expiration = 86400
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'store_s3')
        self.store_s3 = attributes[:'store_s3']
      else
        self.store_s3 = false
      end

      if attributes.key?(:'s3_filepath')
        self.s3_filepath = attributes[:'s3_filepath']
      end

      if attributes.key?(:'s3_bucket')
        self.s3_bucket = attributes[:'s3_bucket']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @template_id.nil?
        invalid_properties.push('invalid value for "template_id", template_id cannot be nil.')
      end

      if @template_id.to_s.length > 12
        invalid_properties.push('invalid value for "template_id", the character length must be smaller than or equal to 12.')
      end

      if @template_id.to_s.length < 12
        invalid_properties.push('invalid value for "template_id", the character length must be greater than or equal to 12.')
      end

      if !@modifications.nil? && @modifications.length > 100
        invalid_properties.push('invalid value for "modifications", number of items must be less than or equal to 100.')
      end

      if !@width.nil? && @width > 4000
        invalid_properties.push('invalid value for "width", must be smaller than or equal to 4000.')
      end

      if !@width.nil? && @width < 100
        invalid_properties.push('invalid value for "width", must be greater than or equal to 100.')
      end

      if !@quality.nil? && @quality > 100
        invalid_properties.push('invalid value for "quality", must be smaller than or equal to 100.')
      end

      if !@quality.nil? && @quality < 1
        invalid_properties.push('invalid value for "quality", must be greater than or equal to 1.')
      end

      if !@expiration.nil? && @expiration > 604800
        invalid_properties.push('invalid value for "expiration", must be smaller than or equal to 604800.')
      end

      if !@expiration.nil? && @expiration < 60
        invalid_properties.push('invalid value for "expiration", must be greater than or equal to 60.')
      end

      if !@filename.nil? && @filename.to_s.length > 100
        invalid_properties.push('invalid value for "filename", the character length must be smaller than or equal to 100.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      if !@filename.nil? && @filename !~ pattern
        invalid_properties.push("invalid value for \"filename\", must conform to the pattern #{pattern}.")
      end

      if !@s3_filepath.nil? && @s3_filepath.to_s.length > 500
        invalid_properties.push('invalid value for "s3_filepath", the character length must be smaller than or equal to 500.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.\/]+$/)
      if !@s3_filepath.nil? && @s3_filepath !~ pattern
        invalid_properties.push("invalid value for \"s3_filepath\", must conform to the pattern #{pattern}.")
      end

      if !@s3_bucket.nil? && @s3_bucket.to_s.length > 63
        invalid_properties.push('invalid value for "s3_bucket", the character length must be smaller than or equal to 63.')
      end

      if !@s3_bucket.nil? && @s3_bucket.to_s.length < 3
        invalid_properties.push('invalid value for "s3_bucket", the character length must be greater than or equal to 3.')
      end

      pattern = Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      if !@s3_bucket.nil? && @s3_bucket !~ pattern
        invalid_properties.push("invalid value for \"s3_bucket\", must conform to the pattern #{pattern}.")
      end

      if !@version.nil? && @version.to_s.length > 50
        invalid_properties.push('invalid value for "version", the character length must be smaller than or equal to 50.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @template_id.nil?
      return false if @template_id.to_s.length > 12
      return false if @template_id.to_s.length < 12
      return false if !@modifications.nil? && @modifications.length > 100
      return false if !@width.nil? && @width > 4000
      return false if !@width.nil? && @width < 100
      return false if !@quality.nil? && @quality > 100
      return false if !@quality.nil? && @quality < 1
      return false if !@expiration.nil? && @expiration > 604800
      return false if !@expiration.nil? && @expiration < 60
      return false if !@filename.nil? && @filename.to_s.length > 100
      return false if !@filename.nil? && @filename !~ Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      return false if !@s3_filepath.nil? && @s3_filepath.to_s.length > 500
      return false if !@s3_filepath.nil? && @s3_filepath !~ Regexp.new(/^[a-zA-Z0-9_\-\.\/]+$/)
      return false if !@s3_bucket.nil? && @s3_bucket.to_s.length > 63
      return false if !@s3_bucket.nil? && @s3_bucket.to_s.length < 3
      return false if !@s3_bucket.nil? && @s3_bucket !~ Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      return false if !@version.nil? && @version.to_s.length > 50
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] template_id Value to be assigned
    def template_id=(template_id)
      if template_id.nil?
        fail ArgumentError, 'template_id cannot be nil'
      end

      if template_id.to_s.length > 12
        fail ArgumentError, 'invalid value for "template_id", the character length must be smaller than or equal to 12.'
      end

      if template_id.to_s.length < 12
        fail ArgumentError, 'invalid value for "template_id", the character length must be greater than or equal to 12.'
      end

      @template_id = template_id
    end

    # Custom attribute writer method with validation
    # @param [Object] modifications Value to be assigned
    def modifications=(modifications)
      if !modifications.nil? && modifications.length > 100
        fail ArgumentError, 'invalid value for "modifications", number of items must be less than or equal to 100.'
      end

      @modifications = modifications
    end

    # Custom attribute writer method with validation
    # @param [Object] width Value to be assigned
    def width=(width)
      if !width.nil? && width > 4000
        fail ArgumentError, 'invalid value for "width", must be smaller than or equal to 4000.'
      end

      if !width.nil? && width < 100
        fail ArgumentError, 'invalid value for "width", must be greater than or equal to 100.'
      end

      @width = width
    end

    # Custom attribute writer method with validation
    # @param [Object] quality Value to be assigned
    def quality=(quality)
      if quality.nil?
        fail ArgumentError, 'quality cannot be nil'
      end

      if quality > 100
        fail ArgumentError, 'invalid value for "quality", must be smaller than or equal to 100.'
      end

      if quality < 1
        fail ArgumentError, 'invalid value for "quality", must be greater than or equal to 1.'
      end

      @quality = quality
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration Value to be assigned
    def expiration=(expiration)
      if expiration.nil?
        fail ArgumentError, 'expiration cannot be nil'
      end

      if expiration > 604800
        fail ArgumentError, 'invalid value for "expiration", must be smaller than or equal to 604800.'
      end

      if expiration < 60
        fail ArgumentError, 'invalid value for "expiration", must be greater than or equal to 60.'
      end

      @expiration = expiration
    end

    # Custom attribute writer method with validation
    # @param [Object] filename Value to be assigned
    def filename=(filename)
      if !filename.nil? && filename.to_s.length > 100
        fail ArgumentError, 'invalid value for "filename", the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      if !filename.nil? && filename !~ pattern
        fail ArgumentError, "invalid value for \"filename\", must conform to the pattern #{pattern}."
      end

      @filename = filename
    end

    # Custom attribute writer method with validation
    # @param [Object] s3_filepath Value to be assigned
    def s3_filepath=(s3_filepath)
      if !s3_filepath.nil? && s3_filepath.to_s.length > 500
        fail ArgumentError, 'invalid value for "s3_filepath", the character length must be smaller than or equal to 500.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.\/]+$/)
      if !s3_filepath.nil? && s3_filepath !~ pattern
        fail ArgumentError, "invalid value for \"s3_filepath\", must conform to the pattern #{pattern}."
      end

      @s3_filepath = s3_filepath
    end

    # Custom attribute writer method with validation
    # @param [Object] s3_bucket Value to be assigned
    def s3_bucket=(s3_bucket)
      if !s3_bucket.nil? && s3_bucket.to_s.length > 63
        fail ArgumentError, 'invalid value for "s3_bucket", the character length must be smaller than or equal to 63.'
      end

      if !s3_bucket.nil? && s3_bucket.to_s.length < 3
        fail ArgumentError, 'invalid value for "s3_bucket", the character length must be greater than or equal to 3.'
      end

      pattern = Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      if !s3_bucket.nil? && s3_bucket !~ pattern
        fail ArgumentError, "invalid value for \"s3_bucket\", must conform to the pattern #{pattern}."
      end

      @s3_bucket = s3_bucket
    end

    # Custom attribute writer method with validation
    # @param [Object] version Value to be assigned
    def version=(version)
      if !version.nil? && version.to_s.length > 50
        fail ArgumentError, 'invalid value for "version", the character length must be smaller than or equal to 50.'
      end

      @version = version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          template_id == o.template_id &&
          modifications == o.modifications &&
          data == o.data &&
          format == o.format &&
          width == o.width &&
          quality == o.quality &&
          export_type == o.export_type &&
          expiration == o.expiration &&
          filename == o.filename &&
          store_s3 == o.store_s3 &&
          s3_filepath == o.s3_filepath &&
          s3_bucket == o.s3_bucket &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [template_id, modifications, data, format, width, quality, export_type, expiration, filename, store_s3, s3_filepath, s3_bucket, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
