=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.13.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module TemplateFox
  class ExtractPdfPagesRequest < ApiModelBase
    # `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
    attr_accessor :export_type

    # URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
    attr_accessor :expiration

    attr_accessor :filename

    attr_accessor :pdf_url

    attr_accessor :pdf_base64

    # 1-indexed page selection. Supports ranges and singles separated by commas, e.g. `1-3, 5, 7-9`. Order is preserved (`5,1,3` outputs those 3 pages in that order).
    attr_accessor :pages

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'export_type' => :'export_type',
        :'expiration' => :'expiration',
        :'filename' => :'filename',
        :'pdf_url' => :'pdf_url',
        :'pdf_base64' => :'pdf_base64',
        :'pages' => :'pages'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'export_type' => :'AppRoutersV1PdfToolsExportType',
        :'expiration' => :'Integer',
        :'filename' => :'String',
        :'pdf_url' => :'String',
        :'pdf_base64' => :'String',
        :'pages' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'filename',
        :'pdf_url',
        :'pdf_base64',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::ExtractPdfPagesRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::ExtractPdfPagesRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'export_type')
        self.export_type = attributes[:'export_type']
      end

      if attributes.key?(:'expiration')
        self.expiration = attributes[:'expiration']
      else
        self.expiration = 86400
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'pdf_url')
        self.pdf_url = attributes[:'pdf_url']
      end

      if attributes.key?(:'pdf_base64')
        self.pdf_base64 = attributes[:'pdf_base64']
      end

      if attributes.key?(:'pages')
        self.pages = attributes[:'pages']
      else
        self.pages = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@expiration.nil? && @expiration > 604800
        invalid_properties.push('invalid value for "expiration", must be smaller than or equal to 604800.')
      end

      if !@expiration.nil? && @expiration < 60
        invalid_properties.push('invalid value for "expiration", must be greater than or equal to 60.')
      end

      if !@filename.nil? && @filename.to_s.length > 100
        invalid_properties.push('invalid value for "filename", the character length must be smaller than or equal to 100.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      if !@filename.nil? && @filename !~ pattern
        invalid_properties.push("invalid value for \"filename\", must conform to the pattern #{pattern}.")
      end

      if @pages.nil?
        invalid_properties.push('invalid value for "pages", pages cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@expiration.nil? && @expiration > 604800
      return false if !@expiration.nil? && @expiration < 60
      return false if !@filename.nil? && @filename.to_s.length > 100
      return false if !@filename.nil? && @filename !~ Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      return false if @pages.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration Value to be assigned
    def expiration=(expiration)
      if expiration.nil?
        fail ArgumentError, 'expiration cannot be nil'
      end

      if expiration > 604800
        fail ArgumentError, 'invalid value for "expiration", must be smaller than or equal to 604800.'
      end

      if expiration < 60
        fail ArgumentError, 'invalid value for "expiration", must be greater than or equal to 60.'
      end

      @expiration = expiration
    end

    # Custom attribute writer method with validation
    # @param [Object] filename Value to be assigned
    def filename=(filename)
      if !filename.nil? && filename.to_s.length > 100
        fail ArgumentError, 'invalid value for "filename", the character length must be smaller than or equal to 100.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.]+$/)
      if !filename.nil? && filename !~ pattern
        fail ArgumentError, "invalid value for \"filename\", must conform to the pattern #{pattern}."
      end

      @filename = filename
    end

    # Custom attribute writer method with validation
    # @param [Object] pages Value to be assigned
    def pages=(pages)
      if pages.nil?
        fail ArgumentError, 'pages cannot be nil'
      end

      @pages = pages
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          export_type == o.export_type &&
          expiration == o.expiration &&
          filename == o.filename &&
          pdf_url == o.pdf_url &&
          pdf_base64 == o.pdf_base64 &&
          pages == o.pages
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [export_type, expiration, filename, pdf_url, pdf_base64, pages].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
