=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TemplateFox
  class JobStatus
    PENDING = "pending".freeze
    PROCESSING = "processing".freeze
    COMPLETED = "completed".freeze
    FAILED = "failed".freeze

    def self.all_vars
      @all_vars ||= [PENDING, PROCESSING, COMPLETED, FAILED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if JobStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #JobStatus"
    end
  end
end
