=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TemplateFox
  # Response for job status query
  class JobStatusResponse < ApiModelBase
    # Job ID
    attr_accessor :id

    # Current job status
    attr_accessor :status

    # Template used for generation
    attr_accessor :template_id

    # Export type (url)
    attr_accessor :export_type

    attr_accessor :filename

    # Whether S3 storage was requested
    attr_accessor :store_s3

    # Job creation timestamp (ISO 8601)
    attr_accessor :created_at

    # Last update timestamp (ISO 8601)
    attr_accessor :updated_at

    attr_accessor :completed_at

    attr_accessor :result_url

    attr_accessor :result_filename

    attr_accessor :result_expires_at

    attr_accessor :result_s3_bucket

    attr_accessor :result_s3_key

    attr_accessor :error_message

    attr_accessor :error_code

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'status' => :'status',
        :'template_id' => :'template_id',
        :'export_type' => :'export_type',
        :'filename' => :'filename',
        :'store_s3' => :'store_s3',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'completed_at' => :'completed_at',
        :'result_url' => :'result_url',
        :'result_filename' => :'result_filename',
        :'result_expires_at' => :'result_expires_at',
        :'result_s3_bucket' => :'result_s3_bucket',
        :'result_s3_key' => :'result_s3_key',
        :'error_message' => :'error_message',
        :'error_code' => :'error_code'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'status' => :'JobStatus',
        :'template_id' => :'String',
        :'export_type' => :'String',
        :'filename' => :'String',
        :'store_s3' => :'Boolean',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'completed_at' => :'String',
        :'result_url' => :'String',
        :'result_filename' => :'String',
        :'result_expires_at' => :'String',
        :'result_s3_bucket' => :'String',
        :'result_s3_key' => :'String',
        :'error_message' => :'String',
        :'error_code' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'filename',
        :'completed_at',
        :'result_url',
        :'result_filename',
        :'result_expires_at',
        :'result_s3_bucket',
        :'result_s3_key',
        :'error_message',
        :'error_code'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::JobStatusResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::JobStatusResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      else
        self.template_id = nil
      end

      if attributes.key?(:'export_type')
        self.export_type = attributes[:'export_type']
      else
        self.export_type = nil
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'store_s3')
        self.store_s3 = attributes[:'store_s3']
      else
        self.store_s3 = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'result_url')
        self.result_url = attributes[:'result_url']
      end

      if attributes.key?(:'result_filename')
        self.result_filename = attributes[:'result_filename']
      end

      if attributes.key?(:'result_expires_at')
        self.result_expires_at = attributes[:'result_expires_at']
      end

      if attributes.key?(:'result_s3_bucket')
        self.result_s3_bucket = attributes[:'result_s3_bucket']
      end

      if attributes.key?(:'result_s3_key')
        self.result_s3_key = attributes[:'result_s3_key']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'error_code')
        self.error_code = attributes[:'error_code']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @template_id.nil?
        invalid_properties.push('invalid value for "template_id", template_id cannot be nil.')
      end

      if @export_type.nil?
        invalid_properties.push('invalid value for "export_type", export_type cannot be nil.')
      end

      if @store_s3.nil?
        invalid_properties.push('invalid value for "store_s3", store_s3 cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @status.nil?
      return false if @template_id.nil?
      return false if @export_type.nil?
      return false if @store_s3.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] template_id Value to be assigned
    def template_id=(template_id)
      if template_id.nil?
        fail ArgumentError, 'template_id cannot be nil'
      end

      @template_id = template_id
    end

    # Custom attribute writer method with validation
    # @param [Object] export_type Value to be assigned
    def export_type=(export_type)
      if export_type.nil?
        fail ArgumentError, 'export_type cannot be nil'
      end

      @export_type = export_type
    end

    # Custom attribute writer method with validation
    # @param [Object] store_s3 Value to be assigned
    def store_s3=(store_s3)
      if store_s3.nil?
        fail ArgumentError, 'store_s3 cannot be nil'
      end

      @store_s3 = store_s3
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          status == o.status &&
          template_id == o.template_id &&
          export_type == o.export_type &&
          filename == o.filename &&
          store_s3 == o.store_s3 &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          completed_at == o.completed_at &&
          result_url == o.result_url &&
          result_filename == o.result_filename &&
          result_expires_at == o.result_expires_at &&
          result_s3_bucket == o.result_s3_bucket &&
          result_s3_key == o.result_s3_key &&
          error_message == o.error_message &&
          error_code == o.error_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, status, template_id, export_type, filename, store_s3, created_at, updated_at, completed_at, result_url, result_filename, result_expires_at, result_s3_bucket, result_s3_key, error_message, error_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
