=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.13.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module TemplateFox
  # A single element modification, addressed by layer name.
  class Modification < ApiModelBase
    # Name of the layer to modify (set via the editor's Layers panel). Matched against the element's `data-layer-name`, falling back to its `id`.
    attr_accessor :name

    attr_accessor :text

    attr_accessor :image_url

    attr_accessor :color

    attr_accessor :background

    attr_accessor :hidden

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'text' => :'text',
        :'image_url' => :'image_url',
        :'color' => :'color',
        :'background' => :'background',
        :'hidden' => :'hidden'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'text' => :'String',
        :'image_url' => :'String',
        :'color' => :'String',
        :'background' => :'String',
        :'hidden' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'text',
        :'image_url',
        :'color',
        :'background',
        :'hidden'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::Modification` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::Modification`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      end

      if attributes.key?(:'background')
        self.background = attributes[:'background']
      end

      if attributes.key?(:'hidden')
        self.hidden = attributes[:'hidden']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 200
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 200.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@text.nil? && @text.to_s.length > 10000
        invalid_properties.push('invalid value for "text", the character length must be smaller than or equal to 10000.')
      end

      if !@image_url.nil? && @image_url.to_s.length > 2000
        invalid_properties.push('invalid value for "image_url", the character length must be smaller than or equal to 2000.')
      end

      pattern = Regexp.new(/^https?:\/\//)
      if !@image_url.nil? && @image_url !~ pattern
        invalid_properties.push("invalid value for \"image_url\", must conform to the pattern #{pattern}.")
      end

      if !@color.nil? && @color.to_s.length > 100
        invalid_properties.push('invalid value for "color", the character length must be smaller than or equal to 100.')
      end

      if !@background.nil? && @background.to_s.length > 100
        invalid_properties.push('invalid value for "background", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 200
      return false if @name.to_s.length < 1
      return false if !@text.nil? && @text.to_s.length > 10000
      return false if !@image_url.nil? && @image_url.to_s.length > 2000
      return false if !@image_url.nil? && @image_url !~ Regexp.new(/^https?:\/\//)
      return false if !@color.nil? && @color.to_s.length > 100
      return false if !@background.nil? && @background.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 200
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 200.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if !text.nil? && text.to_s.length > 10000
        fail ArgumentError, 'invalid value for "text", the character length must be smaller than or equal to 10000.'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] image_url Value to be assigned
    def image_url=(image_url)
      if !image_url.nil? && image_url.to_s.length > 2000
        fail ArgumentError, 'invalid value for "image_url", the character length must be smaller than or equal to 2000.'
      end

      pattern = Regexp.new(/^https?:\/\//)
      if !image_url.nil? && image_url !~ pattern
        fail ArgumentError, "invalid value for \"image_url\", must conform to the pattern #{pattern}."
      end

      @image_url = image_url
    end

    # Custom attribute writer method with validation
    # @param [Object] color Value to be assigned
    def color=(color)
      if !color.nil? && color.to_s.length > 100
        fail ArgumentError, 'invalid value for "color", the character length must be smaller than or equal to 100.'
      end

      @color = color
    end

    # Custom attribute writer method with validation
    # @param [Object] background Value to be assigned
    def background=(background)
      if !background.nil? && background.to_s.length > 100
        fail ArgumentError, 'invalid value for "background", the character length must be smaller than or equal to 100.'
      end

      @background = background
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          text == o.text &&
          image_url == o.image_url &&
          color == o.color &&
          background == o.background &&
          hidden == o.hidden
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, text, image_url, color, background, hidden].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
