=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.9.1

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module TemplateFox
  class PdfVariant
    PDF_A_1B = "pdf/a-1b".freeze
    PDF_A_2B = "pdf/a-2b".freeze
    PDF_A_3B = "pdf/a-3b".freeze

    def self.all_vars
      @all_vars ||= [PDF_A_1B, PDF_A_2B, PDF_A_3B].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PdfVariant.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PdfVariant"
    end
  end
end
