=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TemplateFox
  # Request model for S3 configuration
  class S3ConfigRequest < ApiModelBase
    # S3-compatible endpoint URL. Must start with https://
    attr_accessor :endpoint_url

    # Access key ID for S3 authentication
    attr_accessor :access_key_id

    attr_accessor :secret_access_key

    # S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)
    attr_accessor :bucket_name

    # Default path prefix for uploaded files. Can include slashes for folder structure
    attr_accessor :default_prefix

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'endpoint_url' => :'endpoint_url',
        :'access_key_id' => :'access_key_id',
        :'secret_access_key' => :'secret_access_key',
        :'bucket_name' => :'bucket_name',
        :'default_prefix' => :'default_prefix'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'endpoint_url' => :'String',
        :'access_key_id' => :'String',
        :'secret_access_key' => :'String',
        :'bucket_name' => :'String',
        :'default_prefix' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'secret_access_key',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::S3ConfigRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::S3ConfigRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'endpoint_url')
        self.endpoint_url = attributes[:'endpoint_url']
      else
        self.endpoint_url = nil
      end

      if attributes.key?(:'access_key_id')
        self.access_key_id = attributes[:'access_key_id']
      else
        self.access_key_id = nil
      end

      if attributes.key?(:'secret_access_key')
        self.secret_access_key = attributes[:'secret_access_key']
      end

      if attributes.key?(:'bucket_name')
        self.bucket_name = attributes[:'bucket_name']
      else
        self.bucket_name = nil
      end

      if attributes.key?(:'default_prefix')
        self.default_prefix = attributes[:'default_prefix']
      else
        self.default_prefix = ''
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @endpoint_url.nil?
        invalid_properties.push('invalid value for "endpoint_url", endpoint_url cannot be nil.')
      end

      if @endpoint_url.to_s.length > 200
        invalid_properties.push('invalid value for "endpoint_url", the character length must be smaller than or equal to 200.')
      end

      if @endpoint_url.to_s.length < 10
        invalid_properties.push('invalid value for "endpoint_url", the character length must be greater than or equal to 10.')
      end

      pattern = Regexp.new(/^https:\/\//)
      if @endpoint_url !~ pattern
        invalid_properties.push("invalid value for \"endpoint_url\", must conform to the pattern #{pattern}.")
      end

      if @access_key_id.nil?
        invalid_properties.push('invalid value for "access_key_id", access_key_id cannot be nil.')
      end

      if @access_key_id.to_s.length > 128
        invalid_properties.push('invalid value for "access_key_id", the character length must be smaller than or equal to 128.')
      end

      if @access_key_id.to_s.length < 16
        invalid_properties.push('invalid value for "access_key_id", the character length must be greater than or equal to 16.')
      end

      if !@secret_access_key.nil? && @secret_access_key.to_s.length > 128
        invalid_properties.push('invalid value for "secret_access_key", the character length must be smaller than or equal to 128.')
      end

      if !@secret_access_key.nil? && @secret_access_key.to_s.length < 16
        invalid_properties.push('invalid value for "secret_access_key", the character length must be greater than or equal to 16.')
      end

      if @bucket_name.nil?
        invalid_properties.push('invalid value for "bucket_name", bucket_name cannot be nil.')
      end

      if @bucket_name.to_s.length > 63
        invalid_properties.push('invalid value for "bucket_name", the character length must be smaller than or equal to 63.')
      end

      if @bucket_name.to_s.length < 3
        invalid_properties.push('invalid value for "bucket_name", the character length must be greater than or equal to 3.')
      end

      pattern = Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      if @bucket_name !~ pattern
        invalid_properties.push("invalid value for \"bucket_name\", must conform to the pattern #{pattern}.")
      end

      if !@default_prefix.nil? && @default_prefix.to_s.length > 500
        invalid_properties.push('invalid value for "default_prefix", the character length must be smaller than or equal to 500.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.\/]*$/)
      if !@default_prefix.nil? && @default_prefix !~ pattern
        invalid_properties.push("invalid value for \"default_prefix\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @endpoint_url.nil?
      return false if @endpoint_url.to_s.length > 200
      return false if @endpoint_url.to_s.length < 10
      return false if @endpoint_url !~ Regexp.new(/^https:\/\//)
      return false if @access_key_id.nil?
      return false if @access_key_id.to_s.length > 128
      return false if @access_key_id.to_s.length < 16
      return false if !@secret_access_key.nil? && @secret_access_key.to_s.length > 128
      return false if !@secret_access_key.nil? && @secret_access_key.to_s.length < 16
      return false if @bucket_name.nil?
      return false if @bucket_name.to_s.length > 63
      return false if @bucket_name.to_s.length < 3
      return false if @bucket_name !~ Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      return false if !@default_prefix.nil? && @default_prefix.to_s.length > 500
      return false if !@default_prefix.nil? && @default_prefix !~ Regexp.new(/^[a-zA-Z0-9_\-\.\/]*$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] endpoint_url Value to be assigned
    def endpoint_url=(endpoint_url)
      if endpoint_url.nil?
        fail ArgumentError, 'endpoint_url cannot be nil'
      end

      if endpoint_url.to_s.length > 200
        fail ArgumentError, 'invalid value for "endpoint_url", the character length must be smaller than or equal to 200.'
      end

      if endpoint_url.to_s.length < 10
        fail ArgumentError, 'invalid value for "endpoint_url", the character length must be greater than or equal to 10.'
      end

      pattern = Regexp.new(/^https:\/\//)
      if endpoint_url !~ pattern
        fail ArgumentError, "invalid value for \"endpoint_url\", must conform to the pattern #{pattern}."
      end

      @endpoint_url = endpoint_url
    end

    # Custom attribute writer method with validation
    # @param [Object] access_key_id Value to be assigned
    def access_key_id=(access_key_id)
      if access_key_id.nil?
        fail ArgumentError, 'access_key_id cannot be nil'
      end

      if access_key_id.to_s.length > 128
        fail ArgumentError, 'invalid value for "access_key_id", the character length must be smaller than or equal to 128.'
      end

      if access_key_id.to_s.length < 16
        fail ArgumentError, 'invalid value for "access_key_id", the character length must be greater than or equal to 16.'
      end

      @access_key_id = access_key_id
    end

    # Custom attribute writer method with validation
    # @param [Object] secret_access_key Value to be assigned
    def secret_access_key=(secret_access_key)
      if !secret_access_key.nil? && secret_access_key.to_s.length > 128
        fail ArgumentError, 'invalid value for "secret_access_key", the character length must be smaller than or equal to 128.'
      end

      if !secret_access_key.nil? && secret_access_key.to_s.length < 16
        fail ArgumentError, 'invalid value for "secret_access_key", the character length must be greater than or equal to 16.'
      end

      @secret_access_key = secret_access_key
    end

    # Custom attribute writer method with validation
    # @param [Object] bucket_name Value to be assigned
    def bucket_name=(bucket_name)
      if bucket_name.nil?
        fail ArgumentError, 'bucket_name cannot be nil'
      end

      if bucket_name.to_s.length > 63
        fail ArgumentError, 'invalid value for "bucket_name", the character length must be smaller than or equal to 63.'
      end

      if bucket_name.to_s.length < 3
        fail ArgumentError, 'invalid value for "bucket_name", the character length must be greater than or equal to 3.'
      end

      pattern = Regexp.new(/^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/)
      if bucket_name !~ pattern
        fail ArgumentError, "invalid value for \"bucket_name\", must conform to the pattern #{pattern}."
      end

      @bucket_name = bucket_name
    end

    # Custom attribute writer method with validation
    # @param [Object] default_prefix Value to be assigned
    def default_prefix=(default_prefix)
      if default_prefix.nil?
        fail ArgumentError, 'default_prefix cannot be nil'
      end

      if default_prefix.to_s.length > 500
        fail ArgumentError, 'invalid value for "default_prefix", the character length must be smaller than or equal to 500.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_\-\.\/]*$/)
      if default_prefix !~ pattern
        fail ArgumentError, "invalid value for \"default_prefix\", must conform to the pattern #{pattern}."
      end

      @default_prefix = default_prefix
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          endpoint_url == o.endpoint_url &&
          access_key_id == o.access_key_id &&
          secret_access_key == o.secret_access_key &&
          bucket_name == o.bucket_name &&
          default_prefix == o.default_prefix
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [endpoint_url, access_key_id, secret_access_key, bucket_name, default_prefix].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
