=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.6.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TemplateFox
  # Response for S3 configuration (with masked secret)
  class S3ConfigResponse < ApiModelBase
    # Whether S3 is configured
    attr_accessor :configured

    # S3-compatible endpoint URL
    attr_accessor :endpoint_url

    # Access key ID
    attr_accessor :access_key_id

    # Masked secret access key (shows first 4 and last 4 characters)
    attr_accessor :secret_access_key_masked

    # S3 bucket name
    attr_accessor :bucket_name

    # Default path prefix for uploads
    attr_accessor :default_prefix

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'configured' => :'configured',
        :'endpoint_url' => :'endpoint_url',
        :'access_key_id' => :'access_key_id',
        :'secret_access_key_masked' => :'secret_access_key_masked',
        :'bucket_name' => :'bucket_name',
        :'default_prefix' => :'default_prefix'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'configured' => :'Boolean',
        :'endpoint_url' => :'String',
        :'access_key_id' => :'String',
        :'secret_access_key_masked' => :'String',
        :'bucket_name' => :'String',
        :'default_prefix' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TemplateFox::S3ConfigResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TemplateFox::S3ConfigResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'configured')
        self.configured = attributes[:'configured']
      else
        self.configured = nil
      end

      if attributes.key?(:'endpoint_url')
        self.endpoint_url = attributes[:'endpoint_url']
      else
        self.endpoint_url = nil
      end

      if attributes.key?(:'access_key_id')
        self.access_key_id = attributes[:'access_key_id']
      else
        self.access_key_id = nil
      end

      if attributes.key?(:'secret_access_key_masked')
        self.secret_access_key_masked = attributes[:'secret_access_key_masked']
      else
        self.secret_access_key_masked = nil
      end

      if attributes.key?(:'bucket_name')
        self.bucket_name = attributes[:'bucket_name']
      else
        self.bucket_name = nil
      end

      if attributes.key?(:'default_prefix')
        self.default_prefix = attributes[:'default_prefix']
      else
        self.default_prefix = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @configured.nil?
        invalid_properties.push('invalid value for "configured", configured cannot be nil.')
      end

      if @endpoint_url.nil?
        invalid_properties.push('invalid value for "endpoint_url", endpoint_url cannot be nil.')
      end

      if @access_key_id.nil?
        invalid_properties.push('invalid value for "access_key_id", access_key_id cannot be nil.')
      end

      if @secret_access_key_masked.nil?
        invalid_properties.push('invalid value for "secret_access_key_masked", secret_access_key_masked cannot be nil.')
      end

      if @bucket_name.nil?
        invalid_properties.push('invalid value for "bucket_name", bucket_name cannot be nil.')
      end

      if @default_prefix.nil?
        invalid_properties.push('invalid value for "default_prefix", default_prefix cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @configured.nil?
      return false if @endpoint_url.nil?
      return false if @access_key_id.nil?
      return false if @secret_access_key_masked.nil?
      return false if @bucket_name.nil?
      return false if @default_prefix.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] configured Value to be assigned
    def configured=(configured)
      if configured.nil?
        fail ArgumentError, 'configured cannot be nil'
      end

      @configured = configured
    end

    # Custom attribute writer method with validation
    # @param [Object] endpoint_url Value to be assigned
    def endpoint_url=(endpoint_url)
      if endpoint_url.nil?
        fail ArgumentError, 'endpoint_url cannot be nil'
      end

      @endpoint_url = endpoint_url
    end

    # Custom attribute writer method with validation
    # @param [Object] access_key_id Value to be assigned
    def access_key_id=(access_key_id)
      if access_key_id.nil?
        fail ArgumentError, 'access_key_id cannot be nil'
      end

      @access_key_id = access_key_id
    end

    # Custom attribute writer method with validation
    # @param [Object] secret_access_key_masked Value to be assigned
    def secret_access_key_masked=(secret_access_key_masked)
      if secret_access_key_masked.nil?
        fail ArgumentError, 'secret_access_key_masked cannot be nil'
      end

      @secret_access_key_masked = secret_access_key_masked
    end

    # Custom attribute writer method with validation
    # @param [Object] bucket_name Value to be assigned
    def bucket_name=(bucket_name)
      if bucket_name.nil?
        fail ArgumentError, 'bucket_name cannot be nil'
      end

      @bucket_name = bucket_name
    end

    # Custom attribute writer method with validation
    # @param [Object] default_prefix Value to be assigned
    def default_prefix=(default_prefix)
      if default_prefix.nil?
        fail ArgumentError, 'default_prefix cannot be nil'
      end

      @default_prefix = default_prefix
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          configured == o.configured &&
          endpoint_url == o.endpoint_url &&
          access_key_id == o.access_key_id &&
          secret_access_key_masked == o.secret_access_key_masked &&
          bucket_name == o.bucket_name &&
          default_prefix == o.default_prefix
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [configured, endpoint_url, access_key_id, secret_access_key_masked, bucket_name, default_prefix].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
