=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.12.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module TemplateFox
  class ImageApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Generate image from template
    # Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (`x-api-key` header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | `template_id` | string | ✅ Yes | Template short ID (12 characters) | | `modifications` | array | No | Modify elements by layer name (see below) | | `format` | string | No | `png` (default), `jpeg` or `webp` | | `width` | integer | No | Output width in pixels (defaults to the template's native width) | | `export_type` | string | No | `url` (default) or `binary` |  ## Modifications  Each modification targets a layer by the `name` you set in the editor's Layers panel:  | Property | Description | |----------|-------------| | `name` | Layer name to modify (required) | | `text` | Replace the layer's text | | `image_url` | Set the layer's image (`src` for images, `background-image` otherwise) | | `color` | Text color | | `background` | Background color | | `hidden` | Hide (`true`) or show (`false`) the layer |  Unknown layer names are skipped and listed in the response `warnings`. A name that matches several layers is applied to all of them.  ## Export Types - `url` (default): image is uploaded to CDN, returns JSON with URL - `binary`: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use `/v1/pdf/create` for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
    # @param create_image_request [CreateImageRequest] 
    # @param [Hash] opts the optional parameters
    # @return [CreateImageResponse]
    def create_image(create_image_request, opts = {})
      data, _status_code, _headers = create_image_with_http_info(create_image_request, opts)
      data
    end

    # Generate image from template
    # Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |----------|-------------| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
    # @param create_image_request [CreateImageRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateImageResponse, Integer, Hash)>] CreateImageResponse data, response status code and response headers
    def create_image_with_http_info(create_image_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ImageApi.create_image ...'
      end
      # verify the required parameter 'create_image_request' is set
      if @api_client.config.client_side_validation && create_image_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_image_request' when calling ImageApi.create_image"
      end
      # resource path
      local_var_path = '/v1/image/create'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'image/png']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_image_request)

      # return_type
      return_type = opts[:debug_return_type] || 'CreateImageResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :operation => :"ImageApi.create_image",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ImageApi#create_image\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
