=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.8.1

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

module TemplateFox
  VERSION = '1.8.1'
end
