=begin
#TemplateFox API

#Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

The version of the OpenAPI document: 1.1.1.dev2+gfe6303fdd.d20260209

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

module TemplateFox
  VERSION = '1.0.0'
end
