=begin
#TemplateFox API

#Generate PDFs from HTML templates via API. Design once, generate thousands.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

module TemplateFox
  VERSION = '1.0.1'
end
